### ISSUE TITLE
DBS that aren't LSMs

### ISSUE THREAD

**Issue by faddat** [cosmos/cosmos-db#31]
@ValarDragon mentions:

https://twitter.com/valardragon/status/1558129554312536066

So, while this would conflict with the notion of a pure cgo cosmos-db, it may be worth checking out mdbx.

Also, this issue is generally for collecting information about databases we could use here, that are not LSMs.

**Comment by tac0turtle** [comment]
closing for now as this repo is only used until store rewrite happens
