### ISSUE TITLE
pebble: .DeleteSync has suspicious nil return for error condition as well as extraneous if err != nil + returns that masked the error

### ISSUE THREAD

**Issue by odeke-em** [cosmos/cosmos-db#94]
If we examine this code, it does an unnecessary if err != nil check that then masks a suspicious nil error that was actually non-nil
![image](https://github.com/cosmos/cosmos-db/assets/4898263/3d730701-0a32-4000-96b7-0620cf57cbe2)

If we just did `return condition` as a simple coding style, there wouldn't be any problems

/cc @elias-orijtech @tac0turtle @julienrbrt

**Comment by baabeetaa** [comment]
must be copy and paste `https://github.com/cometbft/cometbft-db/blob/main/rocksdb.go#L140C13-L140C13`

**Comment by odeke-em** [comment]
I've sent a fix in PR https://github.com/cosmos/cosmos-db/pull/95
